name: Deploy iOS and Android App (JS only)
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ development ]
    paths:
    - 'app/**'
  pull_request:
    branches: [ main ]
    paths:
    - 'app/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    name: Install and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 4.x
          expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
          expo-packager: 'npm'
      - run: npm install
      - run: expo publish --release-channel beta
        if: github.ref == 'refs/heads/development'
      - run: expo publish --release-channel production
        if: github.ref == 'refs/heads/main'
